### PR TITLE
feat: update to use Node 20

### PR DESCRIPTION
**Pull request by MLKendall**

### CODE REVIEW

**Review by jonoliver — CHANGES_REQUESTED** [review]
We need to update the version in `package-lock.json` as well. But it looks like we have another issue, our current package lock file referencing sass from localhost instead of the npm registry: https://github.com/sparkbox/downpour/blob/0d561470fdbce3f130b45b2ecb601b26f8bcf8d1/package-lock.json#L4435
It looks like [verdaccio](https://verdaccio.org/) was being used locally, resulting in the wrong registry being erroneously committed. This causes `npm install` to hang and fail currently.

To fix it, I think we need to rebuild the package lock:

```sh
rm package-lock.json
rm -rf node_modules
npm install
```
That should fix the issue and bump the version in the package lock.

**Review by jonoliver — COMMENTED** [review]
I have a few concerns with these updates:

1. A version bump PR should probably be limited to only bumping the version. Code updates should be merged in a preceding PR.
2. I think that bumping up the supported version of node warrants a major version bump. I would consider that a "breaking change" for a project using a node version below 20.

I also think I figured out the issue that was likely causing the build problems. I was able to get CI passing by installing with npm 6:

```sh
npm use 14
cd ~/.nvm/versions/node/v14.21.1/lib
npm install npm@6
```

After that, running npm install to update the package version, CI passed. 

So here's what I'd like to do:
1. I can create a new "Bump to 0.0.13" PR containing just the version bump
1. This is still a valuable PR, but let's update it do describe the dependency/node version updates it's making. 
1. Merge the above two PRs sequentially
1. Create a followup PR to bump the version to `1.0.0`

I think this will give us a better level of granularity on the version bumps while respecting semver. What do you think?

**Comment by jonoliver** [comment]
Created #29 to handle the `0.0.13` version bump in isolation

**Comment by MLKendall** [comment]
Waiting to rebase after 0.0.13 version bump

**Comment by MLKendall** [comment]
Closing this PR to open #30 and #31

**Pull request closed without merging**
